// Generated by gencpp from file openpose_ros_msgs/speed_msgs.msg
// DO NOT EDIT!


#ifndef OPENPOSE_ROS_MSGS_MESSAGE_SPEED_MSGS_H
#define OPENPOSE_ROS_MSGS_MESSAGE_SPEED_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpose_ros_msgs
{
template <class ContainerAllocator>
struct speed_msgs_
{
  typedef speed_msgs_<ContainerAllocator> Type;

  speed_msgs_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , control(0.0)
    , run(0)  {
    }
  speed_msgs_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , control(0.0)
    , run(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _a_type;
  _a_type a;

   typedef double _control_type;
  _control_type control;

   typedef int32_t _run_type;
  _run_type run;





  typedef boost::shared_ptr< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct speed_msgs_

typedef ::openpose_ros_msgs::speed_msgs_<std::allocator<void> > speed_msgs;

typedef boost::shared_ptr< ::openpose_ros_msgs::speed_msgs > speed_msgsPtr;
typedef boost::shared_ptr< ::openpose_ros_msgs::speed_msgs const> speed_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openpose_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'openpose_ros_msgs': ['/home/nvidia/catkin_ws/src/openpose_ros/openpose_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61028b1cdfbf63753def51166b8a3571";
  }

  static const char* value(const ::openpose_ros_msgs::speed_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61028b1cdfbf6375ULL;
  static const uint64_t static_value2 = 0x3def51166b8a3571ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpose_ros_msgs/speed_msgs";
  }

  static const char* value(const ::openpose_ros_msgs::speed_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 a\n\
float64 control\n\
int32 run\n\
\n\
";
  }

  static const char* value(const ::openpose_ros_msgs::speed_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
      stream.next(m.control);
      stream.next(m.run);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpose_ros_msgs::speed_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpose_ros_msgs::speed_msgs_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "control: ";
    Printer<double>::stream(s, indent + "  ", v.control);
    s << indent << "run: ";
    Printer<int32_t>::stream(s, indent + "  ", v.run);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPOSE_ROS_MSGS_MESSAGE_SPEED_MSGS_H
